### application property

server:
  port: 8090
  contextPath: /email-sender

security:
  basic:
    enabled: false

info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}


logging:
  file: email-sender.log
  level: info

### user property
email.sender.user:
  from:


### provider property
email.sender.provider:
  sendgridApiKey: